version: '3.3'

services:

  nginx:
    image: nginx:1.20.1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    volumes:
      # keep in sync with deploy/docker-entrypoint.d/30-copy-static-data.sh
      - source: static
        target: /label-studio/label_studio
        type: volume
        volume:
          nocopy: true
      - ./mydata:/label-studio/data:rw
      - ./deploy/nginx/${NGINX_FILE:-default.conf}:/etc/nginx/conf.d/default.conf:ro
    command: nginx -g "daemon off;"
    restart: always

  app:
    stdin_open: true
    tty: true
    image: heartexlabs/label-studio:1.3.0
    expose:
      - "8080"
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME
      - POSTGRE_USER
      - POSTGRE_PASSWORD
      - POSTGRE_PORT=5432
      - POSTGRE_HOST
      - LABEL_STUDIO_HOST=
      - LABEL_STUDIO_COPY_STATIC_DATA=true
      - LABEL_STUDIO_DISABLE_SIGNUP_WITHOUT_LINK
      - LABEL_STUDIO_USERNAME
      - LABEL_STUDIO_PASSWORD
    volumes:
      - ./mydata:/label-studio/data:rw
      # keep in sync with deploy/docker-entrypoint.d/30-copy-static-data.sh
      - source: static
        target: /label-studio/static_volume
        type: volume
        volume:
          nocopy: true
    restart: always

volumes:
  static: {} 
